### ISSUE TITLE
http://cljs-book.clj.im/ 404

### ISSUE THREAD

**Issue by haydenull** [clojure-china/cljs-book#7]
在线地址 404 了

**Comment by tiye** [comment]
查了一下是路径配置错, 大概是半年多之前迁移的时候迁错了一直没发现... 唉... 临时修了一下.

如果打不开还有个备份的地址 http://r.tiye.me/clojure-china/cljs-book/_book/ .

**Comment by haydenull** [comment]
感谢大佬

**Comment by tiye** [comment]
看样子 ok 了

**Comment by haydenull** [comment]
> 看样子 ok 了

我这边可以正常访问了
